### ISSUE TITLE
Unable to create connection to IS2

### ISSUE THREAD

**Issue by ElenaSavin** [RGLab/ImmuneSignatures2#4]
Hi, when running CreateConnection("IS2", verbose = T, onTest = FALSE) i get an error - IS2 is not one of the available study Ids.
How can i pull or download your gene expression data?

**Comment by helenmiller16** [comment]
Hello, apologies for not seeing your query earlier! Now that the data has been finalized we have updated permissions so that you should be able to create a connection to the IS2 study. Processed data as described in the preprint (https://www.biorxiv.org/content/10.1101/2021.11.05.465336v1) is available directly from ImmuneSpace: https://www.immunespace.org/is2.url 
Hope this helps. Glad to see interest in the data!
